Controllers/UserManagerController.cs
using System.Reflection.Metadata;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Moment.Data;
using Moment.Models.Entity;
using Moment.Models.EntityDto;
using System.Text.Json;

namespace Moment.Controllers
{

    public class UserManagerController : Controller
    {
        private readonly ApplicationDbContext _dbContext;
        private readonly IWebHostEnvironment _hostEnvironment;
        private readonly IMapper _mapper;
        private UserManager<IdentityUser> _userManager;
        private readonly SignInManager<IdentityUser> _signInManager;
        public UserManagerController(UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager, ApplicationDbContext dbContext, IWebHostEnvironment hostEnvironment, IMapper mapper)
        {
            this._dbContext = dbContext;
            this._hostEnvironment = hostEnvironment;
            this._userManager = userManager;
            this._signInManager = signInManager;
            this._mapper = mapper;
        }
        [HttpGet, Authorize, Route("Conta")]
        public async Task<IActionResult> Index(string successMessage, string errorMessage)
        {
            ViewData["Title"] = "Preferências";
            var currentUser = await _userManager.GetUserAsync(User);
            var info = await _dbContext.UserInfos.Where(u => u.IdUser == _userManager.GetUserId(User)).FirstOrDefaultAsync();
            var model = new UserManagerIndexView();

            model.NameUser = currentUser.UserName;
            model.EmailUser = currentUser.Email;
            model.PhoneUser = currentUser.PhoneNumber;
            model.ErrorMessage = errorMessage;
            model.SuccessMessage = successMessage;

            if (info != null)
            {
                _mapper.Map(info, model);
            }

            return View(model);
        }


        [HttpPost, Authorize, Route("/Conta/AtualizaInfos")]
        public async Task<IActionResult> UpdateUser(UserManagerIndexView user, IFormFile profilePicture)
        {
            var model = user;
            var successMessage = "";
            var errorMessage = "";
            var currentUser = await _userManager.GetUserAsync(User);
            if (currentUser == null)
            {
                return NotFound($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
            }

            if (!ModelState.IsValid)
            {
                return BadRequest(new { Message = "Faltou Informações na requisição" });
            }

            var phoneNumber = await _userManager.GetPhoneNumberAsync(currentUser);
            if (model.PhoneUser != phoneNumber)
            {
                var setPhoneResult = await _userManager.SetPhoneNumberAsync(currentUser, model.PhoneUser);

                if (!setPhoneResult.Succeeded)
                {
                    errorMessage = "Erro inesperado ao tentar definir o número de telefone,";
                    return RedirectToAction("Index", model);
                }
            }

            await _signInManager.RefreshSignInAsync(currentUser);

            if (!String.IsNullOrEmpty(model.FirstName))
            {
                var userInfo = await _dbContext.UserInfos.FirstOrDefaultAsync(ui => ui.IdUser == currentUser.Id);

                _mapper.Map(model, userInfo);

                if (profilePicture != null)
                {
                    string wwwRootPath = _hostEnvironment.WebRootPath;

                    if (userInfo.ProfilePicture != null)
                    {
                        string oldFile = Path.Combine(wwwRootPath, userInfo.ProfilePicture.TrimStart('\\'));
                        if (System.IO.File.Exists(oldFile))
                        {
                            System.IO.File.Delete(oldFile);
                        }
                    }
                    string fileName = userInfo.IdUser + Path.GetExtension(profilePicture.FileName);
                    string uploads = Path.Combine(wwwRootPath, @"img\usersPictures");
                    string newFile = Path.Combine(uploads, fileName);
                    using (var stream = new FileStream(newFile, FileMode.Create))
                    {
                        profilePicture.CopyTo(stream);
                    }
                    userInfo.ProfilePicture = @"\img\usersPictures\" + fileName;
                }

                _dbContext.Update(userInfo);
                await _dbContext.SaveChangesAsync();
            }

            successMessage = "Seu perfil foi atualizado";

            var temp = new UserManagerIndexView();
            temp.SuccessMessage = successMessage;
            temp.ErrorMessage = errorMessage;
            return RedirectToAction("Index", new { errorMessage = errorMessage, successMessage = successMessage });
        }

        [HttpGet, Authorize, Route("Conta/MeusEventos")]
        public async Task<IActionResult> MyEvents()
        {
            UserManagerMyEventsView viewModel = new();
            ViewData["Title"] = "Preferências";

            var conventions = new List<EventCard>();
            var idUser = _userManager.GetUserId(User);
            var userInfo = _dbContext.UserInfos.Where(u => u.IdUser == idUser).FirstOrDefault();
            bool isPromoter = userInfo != null ? userInfo.Promoter : false;
            var _conventions = _dbContext.Conventions.Where(c => c.IdUserPromoter == idUser).ToList();
            foreach (var convention in _conventions)
            {
                conventions.Add(new EventCard(convention));
            }
  
            viewModel.IsPromoter = isPromoter;
            viewModel.Conventions = conventions;
            return View(viewModel);
        }

        [HttpGet, Authorize, Route("/Conta/CompletarRegistro")]
        public IActionResult CompleteRegister()
        {
            return View();
        }

        [HttpGet, Authorize, Route("/Conta/Dados")]
        public IActionResult UserData()
        {
            return View();
        }



        [HttpPost, Authorize, Route("/Conta/CompletarRegistro")]
        public async Task<IActionResult> CompleteRegister(UserInfoDto info, IFormFile profilePicture)
        {
            if (ModelState.IsValid)
            {
                var userInfo = new UserInfo();
                _mapper.Map(info, userInfo);

                userInfo.IdUser = _userManager.GetUserId(User);
                userInfo.Promoter = true;

                if (profilePicture != null)
                {
                    string wwwRootPath = _hostEnvironment.WebRootPath;
                    string fileName = userInfo.IdUser + Path.GetExtension(profilePicture.FileName);
                    string uploads = Path.Combine(wwwRootPath, @"img\usersPictures");
                    string newFile = Path.Combine(uploads, fileName);
                    using (var stream = new FileStream(newFile, FileMode.Create))
                    {
                        profilePicture.CopyTo(stream);
                    }
                    userInfo.ProfilePicture = @"\img\usersPictures\" + fileName;
                }

                _dbContext.UserInfos.Add(userInfo);
                await _dbContext.SaveChangesAsync();
                //return View(info);
                return RedirectToAction("BecomeAProducer", "Event");
            }
            else
            {
                return BadRequest();
            }

        }

        [HttpPost, Authorize, Route("Conta/BaixarDados")]
        public async Task<IActionResult> DownloadPersonalData()
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return NotFound($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
            }

            // Only include personal data for download
            var personalData = new Dictionary<string, object>();
            var personalDataProps = typeof(IdentityUser).GetProperties().Where(
                            prop => Attribute.IsDefined(prop, typeof(PersonalDataAttribute)));
            foreach (var p in personalDataProps)
            {
                personalData.Add(p.Name, p.GetValue(user)?.ToString() ?? "null");
            }

            var logins = await _userManager.GetLoginsAsync(user);
            foreach (var l in logins)
            {
                personalData.Add($"{l.LoginProvider} external login provider key", l.ProviderKey);
            }

            var userInfo = await _dbContext.UserInfos.FirstOrDefaultAsync(ui => ui.IdUser == user.Id);
            if(userInfo != null){
                var infos = new UserInfoDto();
                _mapper.Map(userInfo,infos);
                personalData.Add("MoreInfos", infos);
            }

            personalData.Add($"Authenticator Key", await _userManager.GetAuthenticatorKeyAsync(user));

            Response.Headers.Add("Content-Disposition", "attachment; filename=PersonalData.json");
            return new FileContentResult(JsonSerializer.SerializeToUtf8Bytes(personalData), "application/json");
        }

        [HttpGet, Authorize, Route("Conta/DeletarDados")]
        public IActionResult DeletePersonalData(string id)
        {
            return View();
        }

        [HttpGet, Authorize, Route("Conta/ConfirmarDeletarDados")]
        public async Task<IActionResult> ConfirmDeletePersonalData()
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return NotFound($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
            }

            var result = await _userManager.DeleteAsync(user);
            var userId = await _userManager.GetUserIdAsync(user);

Views/UserManager/CompleteRegister.cshtml
@model Moment.Models.EntityDto.UserInfoDto
@{
    ViewData["Title"] = "Completar Registro";
}
<div class="container">
    <form class="my-4" enctype="multipart/form-data" asp-controller="UserManager" asp-action="CompleteRegister">
        <div class="px-4 pt-4 pb-2 bg-secondary text-white">
            <h1 class="title-identity mb-4 text-primary">@ViewData["Title"]</h1>

            <div class="col form-group">
                <label asp-for="ProfilePicture" class="form-label"></label>
                <input class="form-control" type="file" asp-for="ProfilePicture"
                    onchange="readImg(this,'Background-Preview')" accept=".jpg,.jpeg,.png,.gif,.jfif">
                <img id="Background-Preview" src="" alt="" srcset="">
            </div>
            <div class="form-group">
                <label asp-for="FirstName" class="form-label"></label>
                <input asp-for="FirstName" class="form-control">
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="form-label"></label>
                <input asp-for="LastName" class="form-control">
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="row">
                <div class="col-3 form-group">
                    <label asp-for="ZipCodeAddress" class="form-label"></label>
                    <input asp-for="ZipCodeAddress" class="form-control cep"></input>
                    <span asp-validation-for="ZipCodeAddress" class="text-danger"></span>
                </div>
                <div class="col form-group">
                    <label asp-for="StreetAddress" class="form-label"></label>
                    <input asp-for="StreetAddress" class="form-control"></input>
                    <span asp-validation-for="StreetAddress" class="text-danger"></span>
                </div>
                <div class="col-2 form-group">
                    <label asp-for="NumberAddress" class="form-label"></label>
                    <input asp-for="NumberAddress" class="form-control"></input>
                    <span asp-validation-for="NumberAddress" class="text-danger"></span>
                </div>
            </div>

            <div class="row">
                <div class="col form-group">
                    <label asp-for="DistrictAddress" class="form-label"></label>
                    <input asp-for="DistrictAddress" class="form-control"></input>
                    <span asp-validation-for="DistrictAddress" class="text-danger"></span>
                </div>
            </div>
            <div class="row">
                <div class="col form-group">
                    <label asp-for="CityAddress" class="form-label"></label>
                    <input asp-for="CityAddress" class="form-control"></input>
                    <span asp-validation-for="CityAddress" class="text-danger"></span>
                </div>
                <div class="col form-group">
                    <label asp-for="StateAddress" class="form-label"></label>
                    <input asp-for="StateAddress" class="form-control"></input>
                    <span asp-validation-for="StateAddress" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="ComplementAddress" class="form-label"></label>
                <input asp-for="ComplementAddress" class="form-control"></input>
                <span asp-validation-for="ComplementAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CPF" class="form-label"></label>
                <input asp-for="CPF" class="form-control"></input>
                <span asp-validation-for="CPF" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="CNPJ" class="form-label"></label>
                <input asp-for="CNPJ" class="form-control"></input>
                <span asp-validation-for="CNPJ" class="text-danger"></span>
            </div>
        </div>

        <input class="col-10 btn btn-primary btn-lg btn-block w-100 rounded-0" type="submit" value="Completar Registro">

    </form>
</div>

<div class="modal fade" id="loading-modal" role="dialog">
    <div class="modal-dialog modal-sm">
        <!-- Modal content-->
        <div class="modal-content col-1 border-0 p-3 modal-dialog-centered">
            <div class="spinner-border text-primary" role="status">
                <span class="visually-hidden">Loading...</span>
            </div>
        </div>

    </div>
</div>


@section Scripts {
    <partial name="_ValidationScriptsPartial" />
    <script src="~/lib/jquery-mask/dist/jquery.mask.min.js"></script>
    <script src="~/lib/jquery-mask/dist/jquery.mask.js"></script>
    <script src="~/js/cpf_cnpj_cep_validator.js"></script>
}

Views/UserManager/DeletePersonalData.cshtml
<div class="w-100 vh-100 d-flex align-items-center justify-content-center">
    <div class="mt-5 d-flex flex-column align-items-center text-white">
        <h4>Tem certeza que voce deseja excluir seus dados?</h4>
        <div class="row gap-1">
            <a id="delete" asp-controller="UserManager" asp-action="ConfirmDeletePersonalData"
                class="btn btn-danger btn-sm">Confirmar</a>
            <a class="btn btn-secondary mb-1 btn-sm" asp-controller="UserManager" asp-action="UserData">Voltar</a>
        </div>
    </div>

</div>

Views/UserManager/Index.cshtml
@model Moment.Models.EntityDto.UserManagerIndexView
<h1 class="ms-2 text-primary">@ViewData["Title"]</h1>
<div class="d-flex gap-4 text-white">
    <partial name="_UserManagerNavPartial" />
    <div class="w-100">
        <form class="p-4" enctype="multipart/form-data" method="post" asp-controller="UserManager"
            asp-action="UpdateUser">
<div class="badge text-bg-success">@Model.SuccessMessage</div>
<div class="badge text-bg-danger">@Model.ErrorMessage</div>

            <div class="row">
                <div class="col-4 form-group">
                    <label asp-for="NameUser" class="form-label"></label>
                    <input asp-for="NameUser" class="form-control">
                    <span asp-validation-for="NameUser" class="text-danger"></span>
                </div>
                <div class="col-4 form-group">
                    <label asp-for="EmailUser" class="form-label"></label>
                    <input asp-for="EmailUser" class="form-control">
                    <span asp-validation-for="EmailUser" class="text-danger"></span>
                </div>
                <div class="col-4 form-group">
                    <label asp-for="PhoneUser" class="form-label"></label>
                    <input asp-for="PhoneUser" class="form-control">
                    <span asp-validation-for="PhoneUser" class="text-danger"></span>
                </div>
            </div>
            <div class="row">
                <div class="d-flex mt-3">
                    <h3 class="text-primary">Social</h3>
                </div>
                <div class="col-12 form-group">
                    <label asp-for="ProfilePicture" class="form-label"></label>
                    <input type="file" asp-for="ProfilePicture" class="form-control">
                    <span asp-validation-for="ProfilePicture" class="text-danger"></span>
                </div>
                <div class="col-6 form-group">
                    <label asp-for="FirstName" class="form-label"></label>
                    <input asp-for="FirstName" class="form-control">
                    <span asp-validation-for="FirstName" class="text-danger"></span>
                </div>
                <div class="col-6 form-group">
                    <label asp-for="LastName" class="form-label"></label>
                    <input asp-for="LastName" class="form-control">
                    <span asp-validation-for="LastName" class="text-danger"></span>
                </div>
                <div class="d-flex mt-3">
                    <h4 class="text-primary">Endereço</h4>
                </div>
                <div class="col-8 col-md-5 form-group">
                    <label asp-for="StreetAddress" class="form-label"></label>
                    <input asp-for="StreetAddress" class="form-control">
                    <span asp-validation-for="StreetAddress" class="text-danger"></span>
                </div>
                <div class="col-4 col-md-2 form-group">
                    <label asp-for="NumberAddress" class="form-label"></label>
                    <input asp-for="NumberAddress" class="form-control">
                    <span asp-validation-for="NumberAddress" class="text-danger"></span>
                </div>
                <div class="col-12 col-md-5 form-group">
                    <label asp-for="DistrictAddress" class="form-label"></label>
                    <input asp-for="DistrictAddress" class="form-control">
                    <span asp-validation-for="DistrictAddress" class="text-danger"></span>
                </div>
                <div class="col-4 col-md-3 form-group">
                    <label asp-for="ZipCodeAddress" class="form-label"></label>
                    <input asp-for="ZipCodeAddress" class="form-control">
                    <span asp-validation-for="ZipCodeAddress" class="text-danger"></span>
                </div>
                <div class="col-4 col-md-6 form-group">
                    <label asp-for="CityAddress" class="form-label"></label>
                    <input asp-for="CityAddress" class="form-control">
                    <span asp-validation-for="CityAddress" class="text-danger"></span>
                </div>
                <div class="col-4 col-md-3 form-group">
                    <label asp-for="StateAddress" class="form-label"></label>
                    <input asp-for="StateAddress" class="form-control">
                    <span asp-validation-for="StateAddress" class="text-danger"></span>
                </div>
                <div class="col-12 col-md-6 form-group">
                    <label asp-for="ComplementAddress" class="form-label"></label>
                    <input asp-for="ComplementAddress" class="form-control">
                    <span asp-validation-for="ComplementAddress" class="text-danger"></span>
                </div>
            </div>
            <button class="mt-3 btn btn-secondary" type="submit">Salvar Preferencias</button>
        </form>
    </div>
</div>

Views/UserManager/MyEvents.cshtml
@model Moment.Models.EntityDto.UserManagerMyEventsView

<h1 class="ms-2 text-primary">@ViewData["Title"]</h1>
<div class="d-flex gap-4 text-white">
    <partial name="_UserManagerNavPartial" />
    <div class="w-100 text-white py-3">
        <div class="container ">
            <div class="content">

                <div>
                    <header class="px-3">
                        <h6 class="text-primary fs-3 m-0 p-0">Meus Eventos</h6>
                    </header>
                    <div class="row p-3">
                        @if (Model.IsPromoter == true)
                        {
                            if (Model.Conventions.Count > 0)
                            {
                                @foreach (var eventCard in Model.Conventions)
                                {
                                    <div class="col-4 event-thumb-list">
                                        <img class="event-thumb-img" src="@eventCard.ThumbnailPath" />
                                        <content class="event-thumb-info">
                                            <span class="event-thumb-info-title">@eventCard.Name</span>
                                            <span class="event-thumb-info-local">@eventCard.Address</span>
                                            <span class="event-thumb-info-date">@eventCard.Date</span>
                                        </content>
                                        <div class="d-flex flex-column justify-content-center">
                                            <a class="btn btn-primary mb-1 btn-sm" asp-controller="Event" asp-action="EventPage"
                                    asp-route-id="@eventCard.Id">Ver</a>
                                            <a class="btn btn-secondary mb-1 btn-sm" asp-controller="Event" asp-action="EditEvent"
                                    asp-route-id="@eventCard.Id">Editar</a>
                                            <a class="btn btn-danger btn-sm" asp-controller="Event" asp-action="DeleteEvent" method="Get"
                                    asp-route-id="@eventCard.Id">Excluir</a>
                                        </div>
                                    </div>
                                }
                            }
                            else
                            {
                                <h4>Voce ainda não tem eventos</h4>
                                <a class="btn btn-primary btn-sm" asp-controller="Event" asp-action="CreateEvent">Adicionar Evento</a>
                            }
                        }
                        else
                        {
                            <h4>Você ainda não é um Produtor, precisamos de mais informações suas.</h4>
                            <a class="btn btn-primary btn-sm" asp-controller="UserManager" asp-action="CompleteRegister">Virar Promoter</a>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Views/UserManager/UserData.cshtml
@{
    ViewData["Title"] = "Preferências";
    ViewData["Subtitle"] = "Seus Dados";
}
<h1 class="ms-2 text-primary">@ViewData["Title"]</h1>
<div class="d-flex gap-4 text-white">
    <partial name="_UserManagerNavPartial" />
    <div class="w-100 text-white py-3">
        <div class="container ">
            <div class="row w-100 p-0 m-0 pb-sm-5">
                <div class="col-12 p-0 m-0">
                    <form class="p-4 " id="download-data" asp-controller="UserManager" asp-action="DownloadPersonalData"  method="post">
                        <h1 class="title-identity mb-4">@ViewData["SubTitle"]</h1>
                        <p>Sua conta contém dados pessoais que você nos forneceu. Esta página permite que você baixe ou
                            exclua esses dados.</p>
                        <p>
                            <strong>A exclusão desses dados removerá permanentemente sua conta, e isso não poderá ser
                                recuperado.</strong>
                        </p>
                        <div>
                            <button class="btn btn-primary" type="submit">Baixar Dados</button>
                            <a id="delete" asp-controller="UserManager" asp-action="DeletePersonalData" method="get"  class="btn btn-danger">Deletar Dados</a>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
<partial name="_ValidationScriptsPartial" />
}