Models/EntityDto/EventPageView.cs
using System.Globalization;
using Moment.Models.Entity;

namespace Moment.Models.EntityDto
{
    public class EventPageView
    {

        public Guid Id;
        public string? Name;
        public string? Resume;
        public string? Description;
        public string? ThumbnailPath;
        public string? BackgroundPath;
        public string? Terms;
        public string? Date;
        public string? StartDate;

        public UserInfo? UserInfo;

        public decimal Latitude { get; set; }

        public decimal Longitude { get; set; }

        public string? CityAndState { get; set; }

        public bool IsFree { get; set; }

        public List<Convention>? Conventions { get; set; }

        public string EuaStartDate
        {
            get
            {
                return DateTime.Parse(StartDate).ToString("MM/dd/yyyy");
            }
        }

        public string? DateFormated
        {
            get
            {
                if (Date.Contains("00:00"))
                    return Date.Replace("• 00:00","");
                else
                    return Date;
            }
        }
    }


}

Models/ModelsView/EventPageView.cs
using Moment.Models.Entity;

namespace Moment.Models.ModelsView
{
    public class EventPageView
    {

        public Guid Id;
        public string? Name;
        public string? Resume;
        public string? Description;
        public string? Image;
        public string? Terms;
        public string? Date;

        public UserInfo? UserInfo;

        public decimal Latitude { get; set; }

        public decimal Longitude { get; set; }

        public string? Address { get; set; }

        public List<Convention>? Conventions { get; set; }
    }


}

Controllers/ApiController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Moment.Data;
using Moment.Models.EntityDto;

namespace Moment.Controllers;

public class ApiController : Controller
{
    private readonly ApplicationDbContext _context;
    public ApiController (ApplicationDbContext context){
        this._context = context;
    }
    public IActionResult Index()
    {
        return View();
    }

    [HttpGet]
    [Route("api/categorias")]
    public async Task<IActionResult> Categories()
    {
        var conventionCategories = await _context.ConventionCategories.ToListAsync();

        List<CategoryDto> response = new List<CategoryDto>();
        foreach (var cc in conventionCategories)
        {
            response.Add(new CategoryDto(cc));
        }

        return Json(response);
    }


}

Controllers/EventController.cs
using System.Linq;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Moment.Data;
using Moment.Models.Entity;
using Moment.Models.EntityDto;

namespace Moment.Controllers;

public class EventController : Controller
{
    private readonly ApplicationDbContext _context;
    private readonly IWebHostEnvironment _hostEnvironment;
    private readonly IMapper _mapper;
    private UserManager<IdentityUser> _userManager;

    public EventController(UserManager<IdentityUser> userManager, ApplicationDbContext context, IWebHostEnvironment hostEnvironment, IMapper mapper)
    {
        this._context = context;
        this._hostEnvironment = hostEnvironment;
        this._userManager = userManager;
        this._mapper = mapper;
    }
    [Route("SejaUmProdutor")]
    public IActionResult BecomeAProducer()
    {
        return View();
    }

    [HttpGet, Route("Pesquisa")]
    public async Task<IActionResult> Search(string texto, string local, string categoria, int valor)
    {
        var conventions = texto == null ? await _context.Conventions.ToListAsync() : await _context.Conventions.Where(c => c.Name.Contains(texto == null ? "" : texto)).ToListAsync();
        var cities = await _context.Cities.ToListAsync();
        var conventionCategories = await _context.ConventionCategories.ToListAsync();

        conventions = conventions.OrderByDescending(c => c.CreateDate).ToList();

        if (!String.IsNullOrEmpty(local))
        {
            conventions = conventions.Where(c => c.CityAndState.Contains(local)).ToList();
        }

        if (!String.IsNullOrEmpty(categoria))
        {
            var cat = await _context.ConventionCategories.Where(cc => cc.Name == categoria).FirstOrDefaultAsync();
            conventions = conventions.Where(c => c.IdCategory == cat.Id).ToList();
        }

        if (valor == 1 || valor == 2)
        {
            var isFree = valor == 1 ? true : false;
            conventions = conventions.Where(c => c.IsFree == isFree).ToList();
        }

        var searchView = new EventSearchView(texto, local != null ? local : "", categoria, valor);
        searchView.CreateEventCards(conventions);
        searchView.Cities = cities;
        searchView.Categories = new SelectList(_context.ConventionCategories.OrderBy(g => g.Id).ToList(), "Name", "Name", searchView.Categoria);

        return View(searchView);
    }

    [HttpGet, Authorize, Route("Evento/CriarEvento")]
    public IActionResult CreateEvent()
    {
        if (!UserIsPromoter())
            return RedirectToAction("CompleteRegister", "UserManager");

        var eventCreate = new EventCreateView();
        eventCreate.Categories = new SelectList(_context.ConventionCategories.OrderBy(g => g.Id).ToList(), "Id", "Name");
        return View(eventCreate);
    }

    [HttpPost, ValidateAntiForgeryToken, Route("Evento/CriarEvento")]
    public async Task<IActionResult> CreateEvent(EventCreateView eventCreate, IFormFile thumbnailPath, IFormFile backgroundPath)
    {

        if (ModelState.IsValid)
        {
            Console.WriteLine(eventCreate);
            if (thumbnailPath != null)
            {
                string wwwRootPath = _hostEnvironment.WebRootPath;
                string fileName = Guid.NewGuid().ToString() + Path.GetExtension(thumbnailPath.FileName);
                string uploads = Path.Combine(wwwRootPath, @"img\eventThumb");
                string newFile = Path.Combine(uploads, fileName);
                using (var stream = new FileStream(newFile, FileMode.Create))
                {
                    thumbnailPath.CopyTo(stream);
                }
                eventCreate.ThumbnailPath = @"\img\eventThumb\" + fileName;
            }

            if (backgroundPath != null)
            {
                string wwwRootPath = _hostEnvironment.WebRootPath;
                string fileName = Guid.NewGuid().ToString() + Path.GetExtension(backgroundPath.FileName);
                string uploads = Path.Combine(wwwRootPath, @"img\eventBack");
                string newFile = Path.Combine(uploads, fileName);
                using (var stream = new FileStream(newFile, FileMode.Create))
                {
                    backgroundPath.CopyTo(stream);
                }
                eventCreate.BackgroundPath = @"\img\eventBack\" + fileName;
            }

            var convention = new Convention();
            convention.IdUserPromoter = _userManager.GetUserId(User);
            convention.CreateDate = DateTime.Now;

            _mapper.Map(eventCreate, convention);
            _context.Add(convention);


            await _context.SaveChangesAsync();

            return RedirectToAction("CreatedEvent", convention);
        }
        eventCreate.Categories = new SelectList(_context.ConventionCategories.OrderBy(g => g.Id).ToList(), "Id", "Name");
        return View(eventCreate);
    }

    [HttpGet, Authorize, Route("Evento/CriadoComSucesso")]
    public IActionResult CreatedEvent(Convention convention)
    {
        EventCreatedView view = new EventCreatedView();

        view.NameEvent = convention.Name;
        view.IdEvent = convention.Id.ToString();
        return View(view);
    }

    [HttpGet, Authorize, Route("Evento/{id}/Editar")]
    public async Task<IActionResult> EditEvent(string id)
    {
        var convention = await _context.Conventions.Where(c => c.Id.ToString() == id).FirstAsync();
        if (convention == null) return NotFound();

        EventEditView viewModel = new();
        _mapper.Map(convention, viewModel);

        viewModel.Categories = new SelectList(_context.ConventionCategories.OrderBy(g => g.Id).ToList(), "Id", "Name", convention.IdCategory);

        return View(viewModel);
    }

    [HttpPost, ValidateAntiForgeryToken, Route("Evento/{id}/Editar")]
    public async Task<IActionResult> EditEvent(EventEditView eventEdit, IFormFile thumbnailPath, IFormFile backgroundPath)
    {
        if (ModelState.IsValid)
        {
            Console.WriteLine(eventEdit);
            if (thumbnailPath != null)
            {
                string wwwRootPath = _hostEnvironment.WebRootPath;

                if (eventEdit.ThumbnailPath != null)
                {
                    string oldFile = Path.Combine(wwwRootPath, eventEdit.ThumbnailPath.TrimStart('\\'));
                    if (System.IO.File.Exists(oldFile))
                    {
                        System.IO.File.Delete(oldFile);
                    }
                }

                string fileName = Guid.NewGuid().ToString() + Path.GetExtension(thumbnailPath.FileName);
                string uploads = Path.Combine(wwwRootPath, @"img\eventThumb");
                string newFile = Path.Combine(uploads, fileName);
                using (var stream = new FileStream(newFile, FileMode.Create))
                {
                    thumbnailPath.CopyTo(stream);
                }
                eventEdit.ThumbnailPath = @"\img\eventThumb\" + fileName;
            }

            if (backgroundPath != null)
            {
                string wwwRootPath = _hostEnvironment.WebRootPath;


                if (eventEdit.BackgroundPath != null)
                {
                    string oldFile = Path.Combine(wwwRootPath, eventEdit.BackgroundPath.TrimStart('\\'));
                    if (System.IO.File.Exists(oldFile))
                    {
                        System.IO.File.Delete(oldFile);
                    }
                }
                string fileName = Guid.NewGuid().ToString() + Path.GetExtension(backgroundPath.FileName);
                string uploads = Path.Combine(wwwRootPath, @"img\eventBack");
                string newFile = Path.Combine(uploads, fileName);
                using (var stream = new FileStream(newFile, FileMode.Create))
                {
                    backgroundPath.CopyTo(stream);
                }
                eventEdit.BackgroundPath = @"\img\eventBack\" + fileName;
            }

            var convention = await _context.Conventions.Where(c => c.Id.ToString() == eventEdit.Id).FirstAsync();
            convention.IdUserPromoter = _userManager.GetUserId(User);
            convention.CreateDate = DateTime.Now;

            _mapper.Map(eventEdit, convention);
            _context.Update(convention);

            var ct = new City(convention.CityAddress, convention.StateAddress);
            if (!_context.Cities.ToList().Contains(ct))
                _context.Add(ct);

            await _context.SaveChangesAsync();

            return RedirectToAction("EventPage", new { id = convention.Id });
        }
        eventEdit.Categories = new SelectList(_context.ConventionCategories.OrderBy(g => g.Id).ToList(), "Id", "Name", eventEdit.IdCategory);
        return View(eventEdit);
    }


    [HttpGet, Authorize, Route("Evento/{id}/Deletar")]
    public IActionResult DeleteEvent(string id)
    {
        var convention = _context.Conventions.FirstOrDefault(c => c.Id.ToString() == id);

        if (convention == null)
            return BadRequest();

        ViewData["Title"] = $"Deletar Evento - {convention.Name}";
        ViewData["Name"] = convention.Name;
        ViewData["Id"] = convention.Id;
        ViewData["thumbPath"] = convention.ThumbnailPath;
        return View();
    }

    [HttpGet, Authorize, Route("Evento/{id}/ConfirmarDeletar")]
    public async Task<IActionResult> Delete(string id)
    {
        var convention = await _context.Conventions.FirstOrDefaultAsync(c => c.Id.ToString() == id);

        if (convention == null)
            return BadRequest();


        _context.Remove(convention);

        await _context.SaveChangesAsync();
        return RedirectToAction("MyEvents", "UserManager");

    }

    public bool UserIsPromoter()
    {
        var id = _userManager.GetUserId(User);

Controllers/HomeController.cs
using System.Diagnostics;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Moment.Data;
using Moment.Models;
using Moment.Models.Entity;
using Moment.Models.EntityDto;

namespace Moment.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;
    private readonly ApplicationDbContext _context;
    private readonly IMapper _mapper;
    public HomeController(ILogger<HomeController> logger, ApplicationDbContext context, IMapper mapper)
    {
        _mapper = mapper;
        _logger = logger;
        _context = context;
    }

    [HttpGet]
    public async Task<IActionResult> Index()
    {
        var conventions = _context.Conventions.OrderByDescending(c => c.CreateDate).Take(25).ToList();
        var conventionCategories = await _context.ConventionCategories.ToListAsync();
        var cities = await _context.Cities.ToListAsync();

        var categories = new List<CategoryDto>();

        foreach (var item in conventionCategories)
        {
            categories.Add(new CategoryDto(item));
        }

        var homeIndex = new HomeIndexView();

        homeIndex.StartCategory = categories[new Random().Next(categories.Count)];
        homeIndex.Cities = cities;
        homeIndex.Categories = new SelectList(_context.ConventionCategories.OrderBy(g => g.Id).ToList(), "Name", "Name");
        homeIndex.CreateRecentEvents(conventions);
        return View(homeIndex);
    }

    [Route("Privacidade")]
    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }



    [Route("Ajuda")]
    public IActionResult CenterHelp()
    {
        return View();
    }
}

Views/Home/CenterHelp.cshtml
@{
    ViewData["Title"] = "Ajuda";
}
<header class="container mb-2">
    <h1 class="title-page text-white">@ViewBag.Title</h1>
</header>
<div class="container d-flex mb-3 gap-3">
    <div class="col-6">
        <img class="img-fluid" src="~/assets/illustrations/faq.svg" alt="">
    </div>
    <div class="accordion col-6" id="accordionPanelsStayOpenExample">
        <div class="accordion-item">
            <h2 class="accordion-header" id="panelsStayOpen-headingOne">
                <button class="accordion-button" type="button" data-bs-toggle="collapse"
                    data-bs-target="#panelsStayOpen-collapseOne" aria-expanded="true"
                    aria-controls="panelsStayOpen-collapseOne">
                    Accordion Item #1
                </button>
            </h2>
            <div id="panelsStayOpen-collapseOne" class="accordion-collapse collapse show"
                aria-labelledby="panelsStayOpen-headingOne">
                <div class="accordion-body">
                    <strong>This is the first item's accordion body.</strong> It is shown by default, until the collapse
                    plugin adds the appropriate classes that we use to style each element. These classes control the
                    overall appearance, as well as the showing and hiding via CSS transitions. You can modify any of
                    this with custom CSS or overriding our default variables. It's also worth noting that just about any
                    HTML can go within the <code>.accordion-body</code>, though the transition does limit overflow.
                </div>
            </div>
        </div>
        <div class="accordion-item">
            <h2 class="accordion-header" id="panelsStayOpen-headingTwo">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                    data-bs-target="#panelsStayOpen-collapseTwo" aria-expanded="false"
                    aria-controls="panelsStayOpen-collapseTwo">
                    Accordion Item #2
                </button>
            </h2>
            <div id="panelsStayOpen-collapseTwo" class="accordion-collapse collapse"
                aria-labelledby="panelsStayOpen-headingTwo">
                <div class="accordion-body">
                    <strong>This is the second item's accordion body.</strong> It is hidden by default, until the
                    collapse plugin adds the appropriate classes that we use to style each element. These classes
                    control the overall appearance, as well as the showing and hiding via CSS transitions. You can
                    modify any of this with custom CSS or overriding our default variables. It's also worth noting that
                    just about any HTML can go within the <code>.accordion-body</code>, though the transition does limit
                    overflow.
                </div>
            </div>
        </div>
        <div class="accordion-item">
            <h2 class="accordion-header" id="panelsStayOpen-headingThree">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                    data-bs-target="#panelsStayOpen-collapseThree" aria-expanded="false"
                    aria-controls="panelsStayOpen-collapseThree">
                    Accordion Item #3
                </button>
            </h2>
            <div id="panelsStayOpen-collapseThree" class="accordion-collapse collapse"
                aria-labelledby="panelsStayOpen-headingThree">
                <div class="accordion-body">
                    <strong>This is the third item's accordion body.</strong> It is hidden by default, until the
                    collapse plugin adds the appropriate classes that we use to style each element. These classes
                    control the overall appearance, as well as the showing and hiding via CSS transitions. You can
                    modify any of this with custom CSS or overriding our default variables. It's also worth noting that
                    just about any HTML can go within the <code>.accordion-body</code>, though the transition does limit
                    overflow.
                </div>
            </div>
        </div>
    </div>

</div>

Views/Home/EventPage.cshtml
@model Moment.Models.Dto.EventPageView
@{
    ViewData["Title"] = "Pagina do Evento";
}

<div class="page">
    <header class="position-relative">
        <img class="header-event-photo"
            src="https://media-blog.keeperformaturas.com.br/wp-content/uploads/2019/07/O-que-observar-ao-visitar-uma-festa-de-formatura.jpg"
            alt="" srcset="">
        <div class="container py-5">
            <span class="big-title">@Model.Name</span>
            <p class="event-sinopse w-50">
                @Model.Resume
            </p>
            <div class="d-flex gap-2">
                <div class="event-timer">
                    <span>20D : 15H : 30M</span>
                </div>
                <a src="#" class="d-flex flex-column justify-content-center align-items-center event-shop">
                    <i class="bi bi-cart-fill fs-5"></i>
                    <span class="fw-bold">Ingresso</span>
                </a>
            </div>
            <div class="d-flex flex-column mt-3">
                <span class="event-date">@Model.Date</span>
                <span class="event-local">@Model.Address</span>
            </div>
        </div>
    </header>
    <content class="event-info d-block">
        <div class="container d-flex gap-3 py-2 align-items-center">
            <div class="event-description">
                <h6>Descrição</h6>
                <p class="m-0">
                    @Html.Display(Model.Description)
                </p>
            </div>
            <div>
                <iframe
                    src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3686.397409149802!2d-48.54836028561401!3d-22.48926802875831!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x94c7459baabaa92b%3A0xd1b954a115160672!2sEtec%20Comendador%20Jo%C3%A3o%20Rays!5e0!3m2!1spt-BR!2sbr!4v1676387736567!5m2!1spt-BR!2sbr"
                    width="350" height="200" style="border:0;" allowfullscreen="" loading="lazy"
                    referrerpolicy="no-referrer-when-downgrade"></iframe>
            </div>
        </div>
    </content>
    <footer class="">
        <div class="container py-3 d-flex gap-4">
            <a class="event-service-link" href="#">Denunciar Evento</a>
            <a class="event-service-link" href="#">Termos do Evento</a>
        </div>
        <div class="bg-primary">
            <div class="container d-flex py-4 gap-3">
                <article class="col-2 event-card event-promoter">
                    <h6>Organizador</h6>
                    <a class="w-100" href="#">
                        <img class="event-promoter-photo" src="@Model.UserInfo?.ProfilePicture"
                            alt="Foto de Perfil do Promoter" srcset="">
                        <p>@Model.UserInfo?.GetFullName()</p>
                    </a>
                </article>
                <article class="event-card col-10">
                    <h6>Eventos Proximos</h6>
                    <content class="d-flex ">
                        <a href="#" class="event-link-card">
                            <img class="event-link-card-photo"
                                src="https://magazord-public.s3.amazonaws.com/rosaazul/img/2022/06/blog/12016/festa-infantil.jpg"
                                alt="" srcset="">
                            <p class="m-0">Reveillon Vira Jeri</p>
                        </a>
                    </content>
                </article>
            </div>
        </div>
    </footer>
    <div hidden>
        <div id="event-terms">
            @Model.Terms
        </div>
    </div>
</div>

Views/Home/Index.cshtml
@model Moment.Models.EntityDto.HomeIndexView
@{
  ViewData["Title"] = "Bem vindo";
}
<div class="header container pb-4">
  <div class="info-container">
    <div>
      <span class="big-title">@Model.StartCategory.Name</span>
      <p class="info-container-description">@Model.StartCategory.Description
      </p>
      <a id="info-container-button" class="btn btn-white" href="/Categoria/@Model.StartCategory.Name">Saber mais</a>
    </div>
    <partial name="../Shared/_SearchContainer.cshtml" />
  </div>
  <div class="info-container-banner">
    <div class="info-banner">
      <img class="banner" src="@Model.StartCategory.ImagePath" />
    </div>
    <img class="back-banner-1" src="~/assets/imgs/Points.svg" />
    <img class="back-banner-2" src="~/assets/imgs/Points2.svg" />
  </div>
</div>
<div class="bg-secondary pt-5">
  <div class="container">
    <header class="list-thumb-title">
      <h6>Últimos Adicionados</h6>
    </header>
    <div id="list-thumb-content" class="list-thumb-content hidden-scroll">
      @foreach (var eventCard in Model.RecentEvents)
      {
        <a class="event-thumb" asp-controller="Event" asp-action="EventPage" asp-route-id="@eventCard.Id">
          <img class="event-thumb-img" src="@eventCard.ThumbnailPath" />
          <content class="event-thumb-info">
            <span class="event-thumb-info-title">@eventCard.Name</span>
            <span class="event-thumb-info-local">@eventCard.Address</span>
            <span class="event-thumb-info-date">@eventCard.DateFormated</span>
          </content>
        </a>
      }

    </div>
  </div>
</div>

@section Scripts{
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.11.1/jquery.js"></script>
  <partial name="../Shared/_SearchScripts.cshtml" />
  <script>
    jQuery(function ($) {
      $.fn.hScroll = function (amount) {
        amount = amount || 120;
        $(this).bind("DOMMouseScroll mousewheel", function (event) {
          var oEvent = event.originalEvent,
            direction = oEvent.detail ? oEvent.detail * -amount : oEvent.wheelDelta,
            position = $(this).scrollLeft();
          position += direction > 0 ? -amount : amount;
          $(this).scrollLeft(position);
          event.preventDefault();
        })
      };
    });

    $(document).ready(function () {
      $('#list-thumb-content').hScroll(40); // You can pass (optionally) scrolling amount
      // Create array for setTimeouts
    });

    var timeouts = [];
    $("#list-thumb-content").mousemove(function () {

      $(this).addClass("show-scroll");

      // Clear all setTimeouts
      for (var i = 0; i < timeouts.length; i++) {
        clearTimeout(timeouts[i]);
      }

      // Start a new setTimeout to disable scoll after 3 seconds
      timeouts.push(setTimeout(hideScroll, 5000));

    });


    function hideScroll() {

      // Disable scroll in ALL divs with .hover-scroll
      $("#list-thumb-content.show-scroll").removeClass("show-scroll");

    }
  </script>
  <script>
    //Trocar Topo da pagina
    let count = 0;
    let categories;

    async function getCategories() {
      await $.get('@Url.Action("Categories","Api")', result => {
        if (result) {
          categories = result;
        }
      });
    }

    function setSlider() {
      let banner = $('.banner');
      let title = $('.big-title');
      let description = $('.info-container-description');
      let button = $('#info-container-button');
      let category = categories[count];
      banner.attr('src', category.imagePath);
      title.text(category.name);
      description.text(category.description)
      button.attr('href', `/Categoria/${category.name}`);
      setInterval(() => {

        title.animate({ opacity: '0', left: '-80px' }, 500, () => { });
        description.animate({ opacity: '0', left: '-80px' }, 510, () => { });
        button.animate({ opacity: '0', left: '-80px' }, 500, () => { });
        $('.info-banner').animate({ opacity: '0', right: '-80px' }, 500, () => {
          count++;
          if (count >= categories.length)
            count = 0;

          category = categories[count];
          banner.attr('src', category.imagePath);
          title.text(category.name);
          description.text(category.description)
          button.attr('href', `/Categoria/${category.name}`);

          title.animate({ opacity: '1', left: '0px' }, 500, () => { });
          description.animate({ opacity: '1', left: '0px' }, 500, () => { });
          button.animate({ opacity: '1', left: '0px' }, 500, () => { });
          $('.info-banner').animate({ opacity: '1', right: '0px' }, 1000, () => { });
        });
      }, 8000);
    };

    async function execucao() {
      await getCategories();
      setSlider();
    }

    $(document).ready(function () {
      execucao();
    });
  </script>
}